### ISSUE TITLE
System.ArgumentOutOfRangeException: Length cannot be less than zero.

### ISSUE THREAD

**Issue by gerrydoro** [chebum/Supervisor#1]
Hello,
i'm trying to use your program to monitor another program called `ZeroNet.exe`
Following your instruction, i downloaded `supervisor.exe`
Then I placed it into the same folder of the ZeroNet executable
I opened the cmd in the same folder and i ran
`supervisor.exe ZeroNet.exe`
And this happened
```
E:\Programs\ZeroNet>supervisor.exe ZeroNet.exe

System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   in System.String.Substring(Int32 startIndex, Int32 length)
   in Supervisor.Program.ParseArgs(String[] args)
   in Supervisor.Program.Main(String[] args)

E:\Programs\ZeroNet>
```

What am I missing?

P.S: I also tried with the program full path like this
`supervisor "E:\Programs\ZeroNet\ZeroNet.exe"`
but the same error occurs.

**Comment by chebum** [comment]
Hi,
Thank you for filling the issue. I made a fix and release. Please download the updated version here:
https://github.com/chebum/Supervisor/releases/tag/1.1
