### ISSUE TITLE
Run in background?

### ISSUE THREAD

**Issue by rp1231** [chebum/Supervisor#3]
Hi chebum,

I just wanted to ask if it is possible to run this app in the background?

Thanks

**Comment by chebum** [comment]
Hi,

I believe you can run it in background from command line as below:

`start /B supervisor myapp.exe`

**Comment by rp1231** [comment]
I tried that,
but the window still stays.....
![cmd_yY8mL3SgzY](https://user-images.githubusercontent.com/47380919/151602322-11a62081-704f-4246-a960-e4fca1c5f9ad.png)

**Comment by rp1231** [comment]
Doesn't seem like there is a way to do this just by using the commands.

Am currently using autohotkey to run it hidden.

Closing this as there seems to be no better solution at the moment.

**Comment by TheExpertNoob** [comment]
try in PowerShell. You can also save the below as a .ps1 file to run it.
`Start-Process -WindowStyle hidden -FilePath supervisor.exe myapp.exe`
